<?php

/**
 * Implements hook_theme().
 */
function learning_tool_theme($existing, $type, $theme, $path)
{
    return [
        'launch_deep_linking' => [
            'variables' => [
                "deep_linking_return_url" => null,
                'resources' => [],
            ],
        ],
        'launch_resource' => [
            'variables' => [
                // 
                "roles" => [],
                "email" => null,
                "name" => null,
                // 
                "resource" => null,
                // 
                "launch_id" => null,
                "grade_action" => null,
            ],
        ],
    ];
}