<?php

/**
 * Implements hook_theme().
 */
function learning_tool_theme($existing, $type, $theme, $path)
{
    return [
        'deep_linking_launch' => [
            'variables' => [
                "deep_linking_return_url" => null,
                'resources' => [],
            ],
        ],
        'resource_launch' => [
            'variables' => [
                "roles" => [],
                "email" => null,
                "name" => null,
                "custom_message" => null,
            ],
        ],
    ];
}